export declare const SERVICE_FEE: number;
export declare const VALID_DURATION_DAYS: number;
export declare const MAX_DEPOSIT: number;
export declare const MAX_MESSAGE_FILE_BYTES: number;
export declare const MAX_MESSAGE_FILE_UPLOADS: number;
export declare const MAX_SELLER_DESC_CHARS = 650;
export declare const MAX_SELLER_SUMMARY_CHARS = 50;
export declare const MAX_SELLER_SKILLS = 15;
export declare const MAX_REVIEW_CHARS = 650;
export declare const MIN_PASS_LENGTH = 8;
export declare const MAX_PASS_LENGTH = 256;
export declare const EMAIL_REGEX: RegExp;
export declare const MAX_PROFILE_PIC_BYTES: number;
export declare const MAX_SERVICE_PRICE: number;
export declare const MAX_SERVICE_DELIVERY_DAYS: number;
export declare const MAX_SERVICE_REVISIONS: number;
export declare const MAX_SERVICE_FEATURES: number;
export declare const REVISIONS: string[];
export declare const MAX_SERVICE_IMAGE_UPLOADS: number;